Perks and Rules components created
Platzi-Master-C9/booking-ui pull request #140
Opened 2022-04-12 03:51 UTC by 701i

fixes issue #14

2022-04-12 20:14 UTC, gh0stl1m requested changes
@701i What do you think if instead of naming the assets and some texts in the components in Spanish we do it in English? the idea is to write everything in descriptive English, so even if we found the design texts in Spanish the idea is to translate them to English

2022-04-13 14:18 UTC, 701i commented
Translations were done

2022-04-13 18:00 UTC, 701i reviewed
Translations were done

2022-04-17 16:01 UTC, gh0stl1m approved these changes

2022-04-18 14:28 UTC, merged