Filter system
Platzi-Master-C9/booking-ui pull request #195
Opened 2022-05-23 13:21 UTC by simontorresdev

The issue of this pull request is [here](https://github.com/orgs/Platzi-Master-C9/projects/10/views/4)

2022-05-23 14:30 UTC, alexcamachogz approved these changes
LGTM

2022-05-24 01:34 UTC, gh0stl1m approved these changes

2022-05-24 01:34 UTC, gh0stl1m commented on packages/search-engine/__tests__/components/Filters/ModalFilters.test.js
> +    const children = 'Texto de prueba'
@simontorresdev what do you think if instead of hardcoding values we use libraries such as Faker to create these values?

2022-05-24 01:34 UTC, gh0stl1m commented on packages/search-engine/__tests__/components/Filters/PriceFilter.test.js
> +    const maxPrice = 2;
@simontorresdev Same here related to the hardcoding values

2022-05-24 01:57 UTC, Cristhian-Medina requested changes

2022-05-24 01:57 UTC, Cristhian-Medina commented on packages/search-engine/jest.config.js
> +  testEnvironment: "jsdom"
The statement is repeated in lines 5 and 14

2022-05-24 01:57 UTC, Cristhian-Medina commented on packages/search-engine/src/components/Header/index.jsx
> +  const sendFitler = () => {
You have a typo, sendFitler() = sendFilter()

2022-05-24 01:57 UTC, Cristhian-Medina commented on apps/booking-app/pages/index.js
You shouldn’t include the result's page here, to view this page you must enter the route */results*

2022-05-28 18:35 UTC, Cristhian-Medina approved these changes

2022-05-28 18:36 UTC, merged